spring:
    datasource:
        url: jdbc:mysql://localhost:3306/feellog?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
api:
    url: https://api.nlpcloud.io/v1/distilbert-base-uncased-emotion/sentiment
    key: Token 3599edadcb19f8c69cf7d921b428a73d96504566

